FROM openjdk:8-jre-alpine
MAINTAINER rcamps
COPY doctype.war /opt/doctype/lib/
RUN mkdir -p /docker/apps/was/ears/doctype.ear/syscfg/
COPY syscfg/* /docker/apps/was/ears/doctype.ear/syscfg/
ENV SPRING_APPLICATION_JSON='{"spring": {"cloud": {"config": {"server": {"git": {"uri": "/var/lib/doctype/config-repo", "clone-on-start": true}}}}}}'
ENV entorno='docker'
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/doctype/lib/doctype.war"]
VOLUME /var/lib/doctype/config-repo
EXPOSE 8899
